# Generated by Django 3.0.10 on 2020-11-20 11:54

from django.db import migrations


def forwards_func(apps, schema_editor):
    HomePage = apps.get_model("home", "HomePage")
    for page in HomePage.objects.all():
        page.body = [
            ('heading', 'A lovely heading'),
            ('heading', 'Another heading'),
        ]
        page.save()


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_body'),
    ]

    operations = [
        migrations.RunPython(forwards_func, migrations.RunPython.noop),
    ]
